# Generated by Django 3.1.1 on 2020-09-16 18:20

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=pictures.models.picture_directory_path, verbose_name='image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='ajouter le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modifier le')),
            ],
        ),
    ]
